### PR TITLE
Fix docker setup

### PR DESCRIPTION
**Pull request by cburgmer**

### CODE REVIEW

**Comment by glyn** [comment]
I rebased https://github.com/cburgmer/json-path-comparison/pull/38 on this PR. The Raku problem is fixed, but Proposal_A still fails with:
```
FAILED: build/test_compilation/Proposal_A
LANG=en_US.UTF-8 LC_ALL= LC_COLLATE=C bash -c "diff --ignore-space-change <(echo 42) <(proposals/Proposal_A/run.sh ''\\$''[1]'' <<< '[0, 42]' | tr -d ' \n') || diff --ignore-space-change <(echo '[42]') <(proposals/Proposal_A/run.sh ''\\$''[1]'' <<< '[0, 42]' | tr -d ' \n')" > build/test_compilation/Proposal_A
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './selector'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/json-path-comparison/proposals/Proposal_A/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './selector'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/json-path-comparison/proposals/Proposal_A/index.js:2:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by cburgmer** [comment]
Found it.
The selector.js file is generated from the BNF grammar. However I forgot to link it into the build step. Works on my machine, because I have been running the unit tests of the implementation which do generate it.
Will fix.

**Comment by cburgmer** [comment]
Pushed a fix here. I think I works, but Ninja decided to do a full rebuild, so I'm still testing it locally.
Let me know should rebasing fail.

**Comment by glyn** [comment]
After rebasing, the only build failure was in my implementation, so the fix looks good. To be on the safe side, I'm running a full build of this PR in docker before I proceed to look at my implementation. I'll let you know how it goes.

Thanks @cburgmer for your quick work!

**Comment by glyn** [comment]
@cburgmer The docker build of this PR succeeded on my machine, so you're good to merge from my perspective. Thanks again.
